<style type="text/css">
.footer_part_map {
	font-family: Trebuchet MS, Arial, Helvetica, sans-serif;
}
</style>

<p><span class="footer_part_map">The Participation Map  was designed by&nbsp;<a href="http://brant.knutzen.se/" target="_blank">Brant Knutzen</a></span>
<span class="footer_part_map">and  the plugin developed by&nbsp;<a href="http://tlextrait.com/" target="_blank">Thomas Lextrait</a>
and is released under the&nbsp;<a href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_US" target="_blank">Creative Commons  BY-SA license</a></span></p>

<br />

Participation Map <?php echo getBGVersion(); ?><br/>

<a href="http://www.gnu.org/licenses/gpl.html" target="_blank">GNU General Public License v3</a>